OCM_URL = "https://prod.portal.onscale.com/api"
OCM_SOCKET_URL = "wss://sockets.prod.portal.onscale.com/socket"
CONCEPTEV_URL = "https://conceptev.ansys.com/api"
client_id =  '515a5511-a53c-45d9-a41a-93979f132c0b'
authority = 'https://ansysaccount.b2clogin.com/ansysaccount.onmicrosoft.com/B2C_1A_ANSYSID_SIGNUP_SIGNIN'
scope ='https://ansysaccount.onmicrosoft.com/AnsysID/Authentication'
account_name = "conceptev_saas@ansys.com"
job_timeout= 3600