name: CI
on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

env:
  MAIN_PYTHON_VERSION: '3.11'
  PACKAGE_NAME: 'ansys-conceptev-core'
  DOCUMENTATION_CNAME: 'conceptev.docs.pyansys.com'
  MEILISEARCH_API_KEY: ${{ secrets.MEILISEARCH_API_KEY }}
  MEILISEARCH_HOST_URL: ${{ vars.MEILISEARCH_HOST_URL }}
  MEILISEARCH_PUBLIC_API_KEY: ${{ secrets.MEILISEARCH_PUBLIC_API_KEY }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  doc-build:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          sudo apt-get install texlive-latex-extra texlive-xetex texlive-fonts-extra
          # sudo apt-get install libgl1-mesa-glx xvfb texlive-latex-extra latexmk graphviz texlive-xetex texlive-fonts-extra qpdf texlive-xetex xindy

      - name: Verify Pandoc installation
        run: pandoc --version

      - name: "Build documentation without cache"
        uses: ansys/actions/doc-build@fix/doc-build-without-python-cache-new
        # env:
        #   CONCEPTEV_USERNAME: ${{ secrets.CONCEPTEV_USERNAME }}
        #   CONCEPTEV_PASSWORD: ${{ secrets.CONCEPTEV_PASSWORD }}
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          skip-install: true
          sphinxopts: -j auto -W --keep-going
          use-python-cache: false
          check-links: false

      - name: "Build documentation without cache again"
        uses: ansys/actions/doc-build@fix/doc-build-without-python-cache-new
        # env:
        #   CONCEPTEV_USERNAME: ${{ secrets.CONCEPTEV_USERNAME }}
        #   CONCEPTEV_PASSWORD: ${{ secrets.CONCEPTEV_PASSWORD }}
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          skip-install: true
          sphinxopts: -j auto -W --keep-going
          use-python-cache: false
          check-links: false

      - name: "Build documentation with cache"
        uses: ansys/actions/doc-build@fix/doc-build-without-python-cache-new
        env:
          # CONCEPTEV_USERNAME: ${{ secrets.CONCEPTEV_USERNAME }}
          # CONCEPTEV_PASSWORD: ${{ secrets.CONCEPTEV_PASSWORD }}
          PYTHON_NO_CACHE_OPTION: ''
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          skip-install: true
          sphinxopts: -j auto -W --keep-going
          use-python-cache: true
          check-links: false
