name: E2E Tests (manual)

on:
  workflow_dispatch:
    inputs:
      python-version:
        description: "Python version"
        required: false
        default: "3.14"

permissions: {}

jobs:
  tests-e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ansys/optislang:25.2.0-jammy
      credentials:
        username: ansys-bot
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: "Pytest"
        env:
          PYOPTISLANG_DISABLE_OPTISLANG_OUTPUT: true
          ANSYSLMD_LICENSE_FILE: ${{ format('1055@{0}', secrets.LICENSE_SERVER) }}
          POETRY_VIRTUALENVS_CREATE: ${{ vars.POETRY_VIRTUALENVS_CREATE }}
          CONCEPTEV_PASSWORD: ${{ secrets.CONCEPTEV_PASSWORD }}
          PYCONCEPTEV_SETTINGS: "tests/e2e/config.toml"
        uses: ansys/actions/tests-pytest@7d55ff0b9f67c77dae50a286d711ee1ae27b0a25 # v10.2.12
        with:
          python-version: ${{ inputs.python-version }}
          pytest-extra-args: "tests/e2e"
